name: api-enrollfun
services:
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ${DOMAIN_FOLDER}/archivos:/archivos
      - .:/code
    network_mode: host
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      BD_USER: ${BD_USER}
      BD_NAME: ${BD_NAME}
      BD_PASSWORD: ${BD_PASSWORD}
      BD_HOST: ${BD_HOST}
      FLASK_ENV: ${FLASK_ENV}
      DEBUG: ${DEBUG}
      HOST: ${HOST}
      DOMAIN_FOLDER: ${DOMAIN_FOLDER}
      FRONTEND_HOST: ${FRONTEND_HOST}
    command: gunicorn --bind 0.0.0.0:5000 app:app;