"""empty message

Revision ID: 2831e34c38d7
Revises: 5541568fb67a
Create Date: 2025-02-06 16:23:30.060846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2831e34c38d7'
down_revision = '5541568fb67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_column('orden_id')

    # ### end Alembic commands ###
