"""empty message

Revision ID: 487e62bf1eb7
Revises: 7154a1338b8f
Create Date: 2024-01-08 00:39:32.300282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487e62bf1eb7'
down_revision = '7154a1338b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lenguajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lenguajes', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
