"""empty message

Revision ID: 4d8ab7663cb2
Revises: 361e1e22cf4b
Create Date: 2024-02-04 14:01:49.788602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d8ab7663cb2'
down_revision = '361e1e22cf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=255), nullable=True))
        batch_op.alter_column('nombre_completo',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('nombre_completo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
