"""Migracion inicial desde version 0.5

Revision ID: 5541568fb67a
Revises: 
Create Date: 2025-02-06 03:11:28.180156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5541568fb67a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cant_ideal', sa.Integer(), nullable=True),
    sa.Column('cant_max', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('representacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados_inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diaSemana', sa.String(length=45), nullable=True),
    sa.Column('horaInicio', sa.String(length=50), nullable=True),
    sa.Column('horaFin', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lenguajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('celular_alt', sa.String(length=11), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=45), nullable=True),
    sa.Column('fechaInicio', sa.Date(), nullable=True),
    sa.Column('fechaFin', sa.Date(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niveles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('programa', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('representacion', sa.String(length=255), nullable=True),
    sa.Column('lenguaje_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lenguaje_id'], ['lenguajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=True),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('inscripcion_id', sa.Integer(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=True),
    sa.Column('max_alumnos', sa.Integer(), nullable=True),
    sa.Column('representacion', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('estado_inscripcion_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_inscripcion_id'], ['estados_inscripcion.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumnos_cursos',
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('alumno_id', 'curso_id')
    )
    op.create_table('curso_horario',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.PrimaryKeyConstraint('curso_id', 'horario_id')
    )
    op.create_table('curso_profesor',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('usuario_profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('curso_id', 'usuario_profesor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso_profesor')
    op.drop_table('curso_horario')
    op.drop_table('alumnos_cursos')
    op.drop_table('cursos')
    op.drop_table('roles_usuarios')
    op.drop_table('niveles')
    op.drop_table('inscripciones')
    op.drop_table('alumnos')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('lenguajes')
    op.drop_table('horarios')
    op.drop_table('estados_inscripcion')
    op.drop_table('aulas')
    # ### end Alembic commands ###
