"""empty message

Revision ID: 5db2e911051c
Revises: 2831e34c38d7
Create Date: 2025-02-08 19:26:14.326482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db2e911051c'
down_revision = '2831e34c38d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos_cursos', schema=None) as batch_op:
        batch_op.drop_constraint('alumnos_cursos_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('alumnos_cursos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint('cursos_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('cursos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'aulas', ['aula_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'niveles', ['nivel_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.drop_constraint('niveles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lenguajes', ['lenguaje_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('niveles_ibfk_1', 'lenguajes', ['lenguaje_id'], ['id'])

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cursos_ibfk_1', 'aulas', ['aula_id'], ['id'])
        batch_op.create_foreign_key('cursos_ibfk_5', 'niveles', ['nivel_id'], ['id'])

    with op.batch_alter_table('alumnos_cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alumnos_cursos_ibfk_1', 'alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key('alumnos_cursos_ibfk_2', 'cursos', ['curso_id'], ['id'])

    # ### end Alembic commands ###
