"""empty message

Revision ID: 7154a1338b8f
Revises: 
Create Date: 2023-12-16 17:33:31.450120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7154a1338b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('nombre_completo',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('celular',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
        batch_op.create_unique_constraint(None, ['dni'])

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('celular',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('nombre_completo',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###
