"""empty message

Revision ID: 9f366114e509
Revises: 1333462cb1a8
Create Date: 2024-02-04 14:09:01.234089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f366114e509'
down_revision = '1333462cb1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
